export const ERROR_CODES = {
  DUPLICATE_YEAR: "DUPLICATE_YEAR",
  CREATE_YEAR_FAILED: "CREATE_YEAR_FAILED",
  YEAR_NOT_FOUND: "YEAR_NOT_FOUND",
  YEAR_ALREADY_LOCKED: "YEAR_ALREADY_LOCKED",
  YEAR_FETCH_FAILED: "YEAR_FETCH_FAILED",
  LOCK_YEAR_FAILED: "LOCK_YEAR_FAILED",
  YEAR_CREATION_BLOCKED: "YEAR_CREATION_BLOCKED",

  TEAM_EXISTS: "TEAM_EXISTS",
  TEAM_NOT_FOUND: "TEAM_NOT_FOUND",
  TEAM_FETCH_FAILED: "TEAM_FETCH_FAILED",
  TEAMS_FETCH_FAILED: "TEAMS_FETCH_FAILED",
  CREATE_TEAM_FAILED: "CREATE_TEAM_FAILED",
  UPDATE_TEAM_FAILED: "UPDATE_TEAM_FAILED",

  YEAR_PARTICIPANT_ALREADY_EXISTS: "YEAR_PARTICIPANT_ALREADY_EXISTS",
  YEAR_PARTICIPANT_FETCH_FAILED: "YEAR_PARTICIPANT_FETCH_FAILED",
  YEAR_PARTICIPANT_CREATION_FAILED: "YEAR_PARTICIPANT_CREATION_FAILED",
  YEAR_PARTICIPANT_DELETION_FAILED: "YEAR_PARTICIPANT_DELETION_FAILED",
  YEAR_PARTICIPANT_NOT_FOUND_OR_ALREADY_BANNED:
    "YEAR_PARTICIPANT_NOT_FOUND_OR_ALREADY_BANNED",
  YEAR_PARTICIPANT_NOT_BANNED: "YEAR_PARTICIPANT_NOT_BANNED",
  YEAR_PARTICIPANT_NOT_FOUND: "YEAR_PARTICIPANT_NOT_FOUND",
  YEAR_PARTICIPANT_ALREADY_DISQUALIFIED:
    "YEAR_PARTICIPANT_ALREADY_DISQUALIFIED",
  YEAR_PARTICIPANT_DISQUALIFY_FAILED: "YEAR_PARTICIPANT_DISQUALIFY_FAILED",
  YEAR_PARTICIPANT_NOT_DISQUALIFIED: "YEAR_PARTICIPANT_NOT_DISQUALIFIED",
  YEAR_PARTICIPANT_UNDISQUALIFY_FAILED: "YEAR_PARTICIPANT_UNDISQUALIFY_FAILED",

  TEAM_PARTICIPANT_FETCH_FAILED: "TEAM_PARTICIPANT_FETCH_FAILED",
  TEAM_PARTICIPANT_NOT_FOUND: "TEAM_PARTICIPANT_NOT_FOUND",

  PARTICIPANT_BANNED: "PARTICIPANT_BANNED",
  PARTICIPANT_BAN_FAILED: "PARTICIPANT_BAN_FAILED",
  PARTICIPANT_UNBAN_FAILED: "PARTICIPANT_UNBAN_FAILED",
  TEAM_LEAD_BAN_FAILED: "TEAM_LEAD_BAN_FAILED",
  REQUEST_ATTEMPTS_EXCEEDED: "REQUEST_ATTEMPTS_EXCEEDED",

  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  INVALID_REQUEST: "INVALID_REQUEST",

  PROFILE_NOT_FOUND: "PROFILE_NOT_FOUND",
  PROFILE_LOOKUP_FAILED: "PROFILE_LOOKUP_FAILED",
  PROFILE_CREATION_FAILED: "PROFILE_CREATION_FAILED",

  YEAR_ACCESS_CHECK_FAILED: "YEAR_ACCESS_CHECK_FAILED",
  YEAR_ACCESS_FETCH_FAILED: "YEAR_ACCESS_FETCH_FAILED",
  YEAR_ACCESS_REQUEST_FAILED: "YEAR_ACCESS_REQUEST_FAILED",
  YEAR_ACCESS_REQUEST_NOT_AVAILABLE: "YEAR_ACCESS_REQUEST_NOT_AVAILABLE",
  YEAR_ACCESS_REQUEST_APPROVE_FAILED: "YEAR_ACCESS_REQUEST_APPROVE_FAILED",
  YEAR_ACCESS_REQUEST_REJECT_FAILED: "YEAR_ACCESS_REQUEST_REJECT_FAILED",

  TEAM_MEMBERSHIP_FETCH_FAILED: "TEAM_MEMBERSHIP_FETCH_FAILED",
  TEAM_MEMBERSHIP_ALREADY_EXISTS: "TEAM_MEMBERSHIP_ALREADY_EXISTS",
  TEAM_MEMBERSHIP_NOT_FOUND: "TEAM_MEMBERSHIP_NOT_FOUND",
  TEAM_MEMBERSHIP_INVALID: "TEAM_MEMBERSHIP_INVALID",
  TEAM_MEMBERSHIP_DELETE_FAILED: "TEAM_MEMBERSHIP_DELETE_FAILED",
  TEAM_MEMBERSHIP_TRANSFER_FAILED: "TEAM_MEMBERSHIP_TRANSFER_FAILED",
  TEAM_MEMBERSHIP_UPDATE_FAILED: "TEAM_MEMBERSHIP_UPDATE_FAILED",

  TEAM_LEAD_ALREADY_EXISTS: "TEAM_LEAD_ALREADY_EXISTS",
  USER_NOT_REGISTERED: "USER_NOT_REGISTERED",
  YEAR_ACCESS_NOT_APPROVED: "YEAR_ACCESS_NOT_APPROVED",
  NOT_A_TEAM_LEAD: "NOT_A_TEAM_LEAD",

  ROLE_OUT_OF_SYNC: "ROLE_OUT_OF_SYNC",
  INVALID_ROLE_TRANSITION: "INVALID_ROLE_TRANSITION",
  ROLE_CHANGE_FAILED: "ROLE_CHANGE_FAILED",

  USERS_FETCH_FAILED: "USERS_FETCH_FAILED",

  APP_USERS_FETCH_FAILED: "APP_USERS_FETCH_FAILED",
  APP_USERS_NOT_FOUND: "APP_USERS_NOT_FOUND",

  INVALID_FILE_UPLOAD: "INVALID_FILE_UPLOAD",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
