export const ERROR_CODES = {
  DUPLICATE_YEAR: 'DUPLICATE_YEAR',
  CREATE_YEAR_FAILED: 'CREATE_YEAR_FAILED',
  YEAR_NOT_FOUND: 'YEAR_NOT_FOUND',
  YEAR_ALREADY_LOCKED: 'YEAR_ALREADY_LOCKED',
  YEAR_FETCH_FAILED: 'YEAR_FETCH_FAILED',
  LOCK_YEAR_FAILED: 'LOCK_YEAR_FAILED',

  TEAM_EXISTS: 'TEAM_EXISTS',
  TEAM_NOT_FOUND: 'TEAM_NOT_FOUND',
  TEAM_FETCH_FAILED: 'TEAM_FETCH_FAILED',
  TEAMS_FETCH_FAILED: 'TEAMS_FETCH_FAILED',
  CREATE_TEAM_FAILED: 'CREATE_TEAM_FAILED',
  UPDATE_TEAM_FAILED: 'UPDATE_TEAM_FAILED',

  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',

  PROFILE_NOT_FOUND: 'PROFILE_NOT_FOUND',
  PROFILE_LOOKUP_FAILED: 'PROFILE_LOOKUP_FAILED',

  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
