export const ERROR_CODES = {
  DUPLICATE_YEAR: 'DUPLICATE_YEAR',
  CREATE_YEAR_FAILED: 'CREATE_YEAR_FAILED',
  YEAR_NOT_FOUND: 'YEAR_NOT_FOUND',
  YEAR_ALREADY_LOCKED: 'YEAR_ALREADY_LOCKED',
  YEAR_FETCH_FAILED: 'YEAR_FETCH_FAILED',
  LOCK_YEAR_FAILED: 'LOCK_YEAR_FAILED',
  YEAR_CREATION_BLOCKED: 'YEAR_CREATION_BLOCKED',

  TEAM_EXISTS: 'TEAM_EXISTS',
  TEAM_NOT_FOUND: 'TEAM_NOT_FOUND',
  TEAM_FETCH_FAILED: 'TEAM_FETCH_FAILED',
  TEAMS_FETCH_FAILED: 'TEAMS_FETCH_FAILED',
  CREATE_TEAM_FAILED: 'CREATE_TEAM_FAILED',
  UPDATE_TEAM_FAILED: 'UPDATE_TEAM_FAILED',

  YEAR_PARTICIPANT_ALREADY_EXISTS: 'YEAR_PARTICIPANT_ALREADY_EXISTS',
  YEAR_PARTICIPANT_FETCH_FAILED: 'YEAR_PARTICIPANT_FETCH_FAILED',
  YEAR_PARTICIPANT_CREATION_FAILED: 'YEAR_PARTICIPANT_CREATION_FAILED',

  PARTICIPANT_BANNED: 'PARTICIPANT_BANNED',
  REQUEST_ATTEMPTS_EXCEEDED: 'REQUEST_ATTEMPTS_EXCEEDED',

  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',

  PROFILE_NOT_FOUND: 'PROFILE_NOT_FOUND',
  PROFILE_LOOKUP_FAILED: 'PROFILE_LOOKUP_FAILED',
  PROFILE_CREATION_FAILED: 'PROFILE_CREATION_FAILED',

  YEAR_ACCESS_CHECK_FAILED: 'YEAR_ACCESS_CHECK_FAILED',
  YEAR_ACCESS_FETCH_FAILED: 'YEAR_ACCESS_FETCH_FAILED',
  YEAR_ACCESS_REQUEST_FAILED: 'YEAR_ACCESS_REQUEST_FAILED',
  YEAR_ACCESS_REQUEST_NOT_AVAILABLE: 'YEAR_ACCESS_REQUEST_NOT_AVAILABLE',
  YEAR_ACCESS_REQUEST_APPROVE_FAILED: 'YEAR_ACCESS_REQUEST_APPROVE_FAILED',
  YEAR_ACCESS_REQUEST_REJECT_FAILED: 'YEAR_ACCESS_REQUEST_REJECT_FAILED',

  TEAM_MEMBERSHIP_FETCH_FAILED: 'TEAM_MEMBERSHIP_FETCH_FAILED',

  INVALID_FILE_UPLOAD: 'INVALID_FILE_UPLOAD',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
